alter table public.gemini_models
  add column if not exists supports_file_search boolean not null default false;

alter table public.gemini_models
  add column if not exists supports_structured_outputs boolean not null default false;

insert into public.gemini_models (
  name,
  base_model_id,
  version,
  display_name,
  description,
  input_token_limit,
  output_token_limit,
  supported_generation_methods,
  thinking,
  temperature,
  max_temperature,
  top_p,
  top_k,
  supports_text,
  supports_image,
  supports_audio,
  supports_video,
  supports_google_search,
  supports_url_context,
  supports_code_execution,
  supports_function_calling,
  supports_tools,
  supports_file_search,
  supports_structured_outputs,
  supports_streaming,
  supports_reasoning,
  is_enabled,
  is_default,
  sort_order
)
values (
  'gemini-3-flash-preview',
  'gemini-3-flash',
  'preview',
  'Gemini 3 Flash Preview',
  'Gemini 3 Flash Preview：支持文本、图像、音频、视频与 PDF 输入，具备 Google Search、URL Context、Code Execution、File Search、Structured Outputs、Function Calling 与 Thinking 能力。',
  1048576,
  65536,
  array['generateContent', 'countTokens'],
  true,
  1.000,
  2.000,
  0.9500,
  64,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  10
)
on conflict (name) do update
set
  base_model_id = excluded.base_model_id,
  version = excluded.version,
  display_name = excluded.display_name,
  description = excluded.description,
  input_token_limit = excluded.input_token_limit,
  output_token_limit = excluded.output_token_limit,
  supported_generation_methods = excluded.supported_generation_methods,
  thinking = excluded.thinking,
  temperature = excluded.temperature,
  max_temperature = excluded.max_temperature,
  top_p = excluded.top_p,
  top_k = excluded.top_k,
  supports_text = excluded.supports_text,
  supports_image = excluded.supports_image,
  supports_audio = excluded.supports_audio,
  supports_video = excluded.supports_video,
  supports_google_search = excluded.supports_google_search,
  supports_url_context = excluded.supports_url_context,
  supports_code_execution = excluded.supports_code_execution,
  supports_function_calling = excluded.supports_function_calling,
  supports_tools = excluded.supports_tools,
  supports_file_search = excluded.supports_file_search,
  supports_structured_outputs = excluded.supports_structured_outputs,
  supports_streaming = excluded.supports_streaming,
  supports_reasoning = excluded.supports_reasoning,
  is_enabled = excluded.is_enabled,
  is_default = excluded.is_default,
  sort_order = excluded.sort_order;
